In [1]:
import numpy as np

In [59]:
A = np.array([[3,1,-1],[1,2,0],[0,1,2],[1,1,-1]])
b = np.array([-3,-3,8,9])
print(A)

[[ 3  1 -1]
 [ 1  2  0]
 [ 0  1  2]
 [ 1  1 -1]]


In [60]:
At = A.T

In [61]:
print(At)

[[ 3  1  0  1]
 [ 1  2  1  1]
 [-1  0  2 -1]]


In [62]:
M = np.dot(At,A)
bt = np.dot(At,b)

print(M)
print(bt)

[[11  6 -4]
 [ 6  7  0]
 [-4  0  6]]
[-3  8 10]


In [63]:
x = np.linalg.solve(M,bt)
print(x)

[-1.  2.  1.]


In [66]:
# La proyeccion ortogonal de b sobre el sub-espacio es
p = np.dot(A,x)
print(np.round(p,4))

[-2.  3.  4. -0.]


In [68]:
# Para Gram-Schmidt definimos los vetores en una matriz
V = np.array([[3,1,0,1],[1,2,1,1],[-1,0,2,-1]])
print(V)

[[ 3  1  0  1]
 [ 1  2  1  1]
 [-1  0  2 -1]]


$$ u_{k} = v_{k} - \sum_{j=1}^{k-1} \frac{<v_{k},u_{j}>}{<u_{j},u_{j}>} u_{j} $$

In [69]:
def GetBase(v, normal = True):
    
    u = np.zeros((v.shape[0],v.shape[1]))
    
    
    for k in range(v.shape[0]):   
        
        u[k] = v[k]
        
        for j in range(k):
            u[k] -= np.dot(v[k],u[j])/np.dot(u[j],u[j])*u[j]
        
        if normal:
           # print(np.linalg.norm(u[k]))
            u[k] /= np.linalg.norm(u[k])
    
    return u

In [87]:
Base = GetBase(V,True)
print('La base ortonormal es: \n',np.round(Base,4))

La base ortonormal es: 
 [[ 0.9045  0.3015  0.      0.3015]
 [-0.3296  0.7534  0.518   0.2354]
 [ 0.2563 -0.2698  0.7825 -0.4992]]


In [88]:
# Los coeficientes en esa base
c = np.zeros(Base.shape[0])
# Los vectores base lo multiplicamos por los coeficientes
v = Base.copy()

for i in range(Base.shape[0]):
    c[i] = np.dot(b,Base[i])
    v[i] = Base[i]*c[i]
     
print(c)
print(v)

[-0.90453403  4.99134506  1.807842  ]
[[-0.81818182 -0.27272727 -0.         -0.27272727]
 [-1.64523282  3.76053215  2.58536585  1.1751663 ]
 [ 0.46341463 -0.48780488  1.41463415 -0.90243902]]


In [89]:
# La proyeccion por gram - schmidt
p = np.sum(v,axis=0)
print(np.round(p,4))

[-2.  3.  4.  0.]
