In [1]:
import numpy as np

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2.,1.,4.]])

In [3]:
print(M)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]


In [31]:
def GetDiagMatrix(M):
    
    M_ = M.copy()
    n = M_.shape[0]
    
    for i in range(n):
        
        # En caso de necesitar la triangular unitaria
       # M_[i,:] /= M_[i,i]
        
        for j in range(i+1,n):
            
            a = M_[j,i]/M_[i,i]  
            # Tomar el primer elemento de la segunda fila y dividirlo por el primer elemento de la primera
            
            
            M_[j,:] -= a*M_[i,:]
            
            # Restar filas
            
    return M_

In [32]:
DM = GetDiagMatrix(M)

In [33]:
print(DM)

[[ 3.         -1.         -1.        ]
 [ 0.          2.66666667  0.66666667]
 [ 0.          0.          4.25      ]]
