In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

In [2]:
M = np.array( [[3,-1,-1],[-1,3,1],[2,1,4]] )
print(M)

[[ 3 -1 -1]
 [-1  3  1]
 [ 2  1  4]]


In [3]:
b = np.array([1,3,7])
print(b)

print(M.shape[1])

[1 3 7]
3


In [4]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [15]:
def GetJacobiMethod(Matrix, bvector, itmax, error):
    
    n = Matrix.shape[1]
    
    x = np.zeros(n)

    sumk = np.zeros(n)
    
    it = 0
    
    residuo = np.linalg.norm( bvector - np.dot(Matrix,x) ) # Metrica
    
    while residuo > error and it < itmax:
        
        it += 1
        
        for i in range(Matrix.shape[0]):
            sum_ = 0
            for j in range(Matrix.shape[1]):
                if i!=j:
                    sum_ += Matrix[i][j]*x[j]
                    
            sumk[i] = sum_
            
        for i in range(Matrix.shape[0]):
            
            if Matrix[i,i] !=0:
                x[i] = (bvector[i] - sumk[i])/Matrix[i,i]
            else:
                print('No invertirble con Jacobi')
                return
        
        
        #print(x)
        #print(residuo)
        residuo = np.linalg.norm( bvector - np.dot(Matrix,x) )    
    
    return x,it,residuo

In [18]:
Xsol, it, error = GetJacobiMethod(M,b,1000,1e-10)
print(Xsol)

[1. 1. 1.]


In [19]:
print(it)

23


In [20]:
def GetTMatrix(Matrix):
    
    n = Matrix.shape[1]
    
    D = np.zeros((n,n))
    R = np.zeros((n,n))
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            if i == j:
                D[i,j] = 1/Matrix[i,i]
            else:
                R[i,j] = Matrix[i,j]
                
    T = np.dot(D,R)
    return T

In [21]:
T = GetTMatrix(M)
print(T)

[[ 0.         -0.33333333 -0.33333333]
 [-0.33333333  0.          0.33333333]
 [ 0.5         0.25        0.        ]]


In [22]:
valores, vectores = np.linalg.eig(T)

In [23]:
print(valores)

[-0.33333333+0.j          0.16666667+0.23570226j  0.16666667-0.23570226j]


In [24]:
print(np.amax(abs(valores)))

0.33333333333333315


In [25]:
IM = np.linalg.inv(M)
print(IM)

[[ 0.32352941  0.08823529  0.05882353]
 [ 0.17647059  0.41176471 -0.05882353]
 [-0.20588235 -0.14705882  0.23529412]]


In [26]:
np.round(np.dot(IM,M),3)

array([[ 1.,  0., -0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [ ]:
# Definamos Gauss-Seidel
def GetGaussSeidelMethod(Matrix, bvector, itmax, error):
    
    n = Matrix.shape[1]
    x = np.zeros(n)
    
    
