In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

In [2]:
M = np.array( [[3,-1,-1],[-1,3,1],[2,1,4]] )
print(M)

[[ 3 -1 -1]
 [-1  3  1]
 [ 2  1  4]]


In [5]:
b = np.array([1,3,7])
print(b)

print(M.shape[1])

[1 3 7]
3


In [19]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [51]:
def GetJacobiMethod(Matrix, bvector, itmax, error):
    
    n = Matrix.shape[1]
    
    #x = np.zeros(n)
    
    x = np.array([15050,4646,4664])
    
    sumk = np.zeros(n)
    
    it = 0
    
    residuo = np.linalg.norm( bvector - np.dot(Matrix,x) ) # Metrica
    
    while residuo > error and it < itmax:
        
        it += 1
        
        for i in range(Matrix.shape[0]):
            sum_ = 0
            for j in range(Matrix.shape[1]):
                if i!=j:
                    sum_ += Matrix[i][j]*x[j]
                    
            sumk[i] = sum_
            
        for i in range(Matrix.shape[0]):
            
            if Matrix[i,i] !=0:
                x[i] = (bvector[i] - sumk[i])/Matrix[i,i]
            else:
                print('No invertirble con Jacobi')
                return
        
        
        #print(x)
        #print(residuo)
        residuo = np.linalg.norm( bvector - np.dot(Matrix,x) )    
    
    return x,it,residuo

In [52]:
Xsol, it, error = GetJacobiMethod(M,b,100000,1e-5)
print(Xsol)

[0 1 1]


In [41]:
print(it)

9


In [45]:
def GetTMatrix(Matrix):
    
    n = Matrix.shape[1]
    
    D = np.zeros((n,n))
    R = np.zeros((n,n))
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            if i == j:
                D[i,j] = 1/Matrix[i,i]
            else:
                R[i,j] = Matrix[i,j]
                
    T = np.dot(D,R)
    return T

In [47]:
T = GetTMatrix(M)
print(T)

[[ 0.         -0.33333333 -0.33333333]
 [-0.33333333  0.          0.33333333]
 [ 0.5         0.25        0.        ]]


In [48]:
valores, vectores = np.linalg.eig(T)

In [49]:
print(valores)

[-0.33333333+0.j          0.16666667+0.23570226j  0.16666667-0.23570226j]


In [50]:
print(np.amax(abs(valores)))

0.33333333333333315
