In [1]:
import numpy as np
import itertools
from itertools import permutations
from itertools import combinations
from itertools import combinations_with_replacement

https://docs.python.org/es/3/library/itertools.html

In [7]:
l1 = [1,1,2]
l1 = [1,1,2,2,3]
p1 = list( permutations(l1) )

In [9]:
print(len(p1))

120


In [10]:
def GetP(p):
    
    pr = []
    
    for i in p:
        if i not in pr:
            pr.append(i)
            
    return pr

In [11]:
p1 = GetP(p1)

In [13]:
print(len(p1))

30


In [17]:
l2 = [1,1,2]
c1 = list(combinations(l2,2))

In [18]:
print(c1)

[(1, 1), (1, 2), (1, 2)]


In [20]:
Ntrials = 100000

results = np.zeros((Ntrials,3))

for i in range(Ntrials):
    d1 = np.random.randint(1,7)
    d2 = np.random.randint(1,7)
    d3 = np.random.randint(1,7)
    results[i] = [d1,d2,d3]

In [24]:
it = 0

for R in results:
    
    for i in range(len(R)-1):
        
        # Ordenamos la lista
        R.sort()
        
       # print(R)
        
        if R[i] == R[i+1]:
            
            a = R[i]
            
            if a not in R[i+2:] and a not in R[:i]:
                
                it += 1
                
print(it/Ntrials, 5./12.)

0.41429 0.4166666666666667


In [26]:
l = np.zeros((1,3))
it = 0

for i in range(1,7):
        for j in range(1,7):
            for k in range(1,7):
                
                if i == j and j != k:      
                
                    l[0] = [i,j,k]
                    print(l[0])    
                    
                    p = list(permutations(l[0]))
                    print(len(GetP(p)))
                    it += len(GetP(p))   
                    
                
print(it, it/6**3)

[1. 1. 2.]
3
[1. 1. 3.]
3
[1. 1. 4.]
3
[1. 1. 5.]
3
[1. 1. 6.]
3
[2. 2. 1.]
3
[2. 2. 3.]
3
[2. 2. 4.]
3
[2. 2. 5.]
3
[2. 2. 6.]
3
[3. 3. 1.]
3
[3. 3. 2.]
3
[3. 3. 4.]
3
[3. 3. 5.]
3
[3. 3. 6.]
3
[4. 4. 1.]
3
[4. 4. 2.]
3
[4. 4. 3.]
3
[4. 4. 5.]
3
[4. 4. 6.]
3
[5. 5. 1.]
3
[5. 5. 2.]
3
[5. 5. 3.]
3
[5. 5. 4.]
3
[5. 5. 6.]
3
[6. 6. 1.]
3
[6. 6. 2.]
3
[6. 6. 3.]
3
[6. 6. 4.]
3
[6. 6. 5.]
3
90 0.4166666666666667
