In [1]:
import numpy as np

In [6]:
States = []

for i in range(2):
    for j in range(2):
        for k in range(2):
            States.append([i,j,k])
            
States = np.array(States)
print(States)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
